name: Deploy demo

on:
  push:
    tags:
      - v*.*.*

  pull_request:
    branches:
      - master

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pages: write
      id-token: write

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Node.js
        uses: actions/setup-node@v6
        with:
          node-version: '24'

      - name: Install Dependencies
        run: yarn

      - name: Build Project
        run: yarn build

      - name: Archive Files
        run: |
          cp -af lib/xterm-addon-search-bar.js pages
          sed -i 's#<script src="../lib/xterm-addon-search-bar.js"></script>#<script src="xterm-addon-search-bar.js"></script>#g' pages/index.html

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./pages
